downstream_package_name: rear
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-35-x86_64
    - fedora-36-x86_64
    - fedora-rawhide-x86_64
    - centos-stream-8-x86_64
    - centos-stream-9-x86_64
  trigger: pull_request
- job: production_build
  metadata:
    scratch: True
    targets:
    - fedora-latest-stable
    - epel-8
    - epel-9
  trigger: pull_request
specfile_path: packaging/rpm/rear.spec
synced_files:
- .packit.yaml
- dest: rear.spec
  src: packaging/rpm/rear.spec
upstream_project_name: rear
